web/apps/blog/urls.py
from django.urls import path
from . import views
from .feed import LatestPostsFeed, LatestTagPostFeed

app_name = "blog"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<slug:post_slug>/", views.PostView.as_view(), name="post"),
    path(
        "post/<slug:post_slug>/comment", views.CommentCreateView.as_view(), name="comment"
    ),
    path("tag/<tag>/", views.TagView.as_view(), name="tag"),
    path("feed/", LatestPostsFeed(), name="feed"),
    path("feed/<tag>/", LatestTagPostFeed(), name="tag-feed"),
]

web/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flat_views
from django.urls import include, path

from apps.blog import urls as blog_urls
from apps.projects import urls as projects_urls
from apps.events import urls as events_urls
from apps.startpage import views as startpage_views

urlpatterns = [
    path("", startpage_views.view_startpage, name="startpage"),
    path("projects/", include(projects_urls, namespace="projects")),
    path("blog/", include(blog_urls, namespace="blog")),
    path("events/", include(events_urls, namespace="events")),
    path("about/", flat_views.flatpage, {"url": "/about/"}, name="about"),
    path("privacy/", flat_views.flatpage, {"url": "/privacy/"}, name="privacy"),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    from django.conf.urls.static import static

    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% include "head.html" %}
    {% block style %}{% endblock %}
</head>

<body class="d-flex flex-column min-vh-100">

    {% include "navbar.html" %}

    {% block page_hero %}{% endblock %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>

    <br>

    <footer class="mt-auto">
        {% include "footer.html" %}
        {% include "scripts.html" %}
        {% block script %}{% endblock %}
    </footer>

    <br>

</body>

</html>

web/templates/footer.html
{% if request.path != '/' %}
<div class="container">
  <div class="footer row">

    <div class="col col-3 text-center">
      <a href="{% url 'about' %}" title="about">
        <small>about</small>
      </a>
    </div>

    <div class="col col-3 text-center">
      {% if tag %}
      <a href="{% url 'blog:tag-feed' tag %}" title="RSS - {{ tag }}">
        <small>rss</small>
      </a>
      {% else %}
      <a href="{% url 'blog:feed' %}" title="RSS">
        <small>rss</small>
      </a>
      {% endif %}
    </div>

    <div class="col col-3 text-center">
      <a href="https://github.com/rattletat/rattletat.com" title="source">
        <small>source</small>
      </a>
    </div>

    <div class="col col-3 text-center">
      <a href="{% url 'privacy' %}" title="privacy statement">
        <small>privacy</small>
      </a>
    </div>

  </div>
</div>
{% endif %}

web/templates/head.html
{% load static %}
{% load compress %}

<!-- Meta Information -->
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex" />
<meta name="author" content="Michael Brauweiler" />

{% if post %}
<meta property="article:published_time" content="{{post.modified | date:"Y-m-d" }}" />
<meta name="description" content="{{ post.description }}"/>
{% else %}
<meta name="description" content="Rattle:tat Blog & Projects"/>
{% endif %}


<!-- CDN CSS -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha512-rO2SXEKBSICa/AfyhEK5ZqWFCOok1rcgPYfGOqtX35OyiraBg6Xa4NnBJwXgpIRoXeWjcAmcQniMhp22htDc6g==" crossorigin="anonymous" /> -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->


<!-- Local CSS -->
{% compress css inline %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/colors.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/markdown.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/details.css" %}">
{% endcompress %}

<!-- Browser -->
<title>Rattle:tat</title>

web/templates/navbar.html
{% load active %}

<div class="container">
    <nav class="navbar navbar-expand-md navbar-light">

        {% if request.path != '/' %}
        <nav class="navbar navbar-default mr-auto">
            <div class="navbar-header">
                <a class="navbar-brand" id="brand" href="{% url 'startpage' %}">Rattle:tat</a>
            </div>
        </nav>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbar-navigation" aria-controls="navbar-navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-right" id="navbar-navigation">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link {% active request 'projects:index' %}"
                    href="{% url 'projects:index' %}">projects</a>
                <a class="nav-item nav-link {% active request 'blog:index' %}" href="{% url 'blog:index' %}">blog</a>
                <a class="nav-item nav-link {% active request 'events:index' %}" href="{% url 'events:index' %}">events</a>
                <label for="darkSwitch" class="nav-item nav-link" style="cursor:pointer">invert</label>
                <input type="checkbox" id="darkSwitch" style="display:none" />
            </div>
        </div>
        {% endif %}

    </nav>
</div>

web/templates/scripts.html
{% load static %}
{% load compress %}

<!-- CDN JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha512-I5TkutApDjnWuX+smLIPZNhw+LhTd8WrQhdCKsxCFRSvhFx2km8ZfEpNIhF9nq04msHhOkE8BMOBj5QE07yhMA==" crossorigin="anonymous"></script>

<!-- Local JS -->
{% compress js %}
<script src="{% static "js/sweet-scroll.min.js" %}"></script>
{% endcompress %}

{% compress js inline %}
<script src="{% static "js/dark_switch.js" %}"></script>
{% endcompress %}