web/apps/projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("project/<slug:project_slug>/", views.ProjectView.as_view(), name="detail"),
]

web/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flat_views
from django.urls import include, path

from apps.blog import urls as blog_urls
from apps.projects import urls as projects_urls
from apps.events import urls as events_urls
from apps.startpage import views as startpage_views

urlpatterns = [
    path("", startpage_views.view_startpage, name="startpage"),
    path("projects/", include(projects_urls, namespace="projects")),
    path("blog/", include(blog_urls, namespace="blog")),
    path("events/", include(events_urls, namespace="events")),
    path("about/", flat_views.flatpage, {"url": "/about/"}, name="about"),
    path("privacy/", flat_views.flatpage, {"url": "/privacy/"}, name="privacy"),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    from django.conf.urls.static import static

    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

web/apps/projects/models.py
import os

from django.db import models
from django.shortcuts import reverse
from autoslug import AutoSlugField
from django.utils.text import slugify
from model_utils.models import TimeStampedModel

from apps.blog.models import Post


class Project(TimeStampedModel):
    title = models.CharField(max_length=100)
    slug = AutoSlugField(max_length=500, populate_from="title")
    description = models.TextField()

    def _image_path(self, filename):
        return os.path.join(self.root_path, "images", filename)

    image = models.ImageField(upload_to=_image_path)

    @property
    def root_path(self):
        return os.path.join("projects", slugify(self.title))

    def get_absolute_url(self):
        return reverse("projects:detail", args=[self.pk])

    def __str__(self):
        return self.title


class Component(models.Model):
    project = models.ForeignKey(Project, models.CASCADE)
    position = models.PositiveSmallIntegerField(default=0, editable=True, db_index=True)
    post = models.ForeignKey(Post, models.SET_NULL, null=True, blank=True)

    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        if self.post:
            return reverse("blog:post", args=[self.post])
        else:
            return reverse("projects:detail", args=[self.pk])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["position"]

web/apps/projects/views.py
from .models import Project
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = "projects/index.html"
    model = Project
    ordering = ["-created"]

    def get_queryset(self):
        return Project.objects.all()


class ProjectView(DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_object(self):
        project_slug = self.kwargs["project_slug"]
        return Project.objects.get(slug=project_slug)

web/templates/projects/card.html
{% load humanize %}

<div class="card mb-4 bg-light">
    <div class="card-header">{{ project.title }}</div>
    <img class="card-img-top" src="{{ project.image.url }}">
    <div class="card-body d-flex flex-column">
        <p class="card-text">{{ project.description }}</p>
        <a href="{% url 'projects:detail' project.slug %}"><button type="button" class="mt-auto btn btn-outline-secondary">Read More</button></a>
    </div>
    <div class="card-footer">
        <small class="text-muted">Created {{ project.created | naturaltime }}</small>
    </div>
    {% if project.updated %}
    <div class="card-footer">
        <small class="text-muted">Last updated {{ project.updated | naturaltime }}</small>
    </div>
    {% endif %}
</div>

web/templates/projects/component.html
{% load humanize %}
{% load markdownify %}

<div class="card mb-4 bg-light">

    {% if component.title %}
      <div class="card-header">{{ component.title }}</div>
    {% endif %}

    {% if component.image %}
        <img class="card-img-top" src="component.image.url }}">
    {% endif %}

    <div class="card-body d-flex flex-column">

    {% if component.description %}
        <p class="card-text">{{ component.description | markdownify }}</p>
    {% endif %}

    {% if component.post %}
    <a href="{% url 'blog:post' component.post.pk %}">
        <button type="button" class="mt-auto btn btn-outline-secondary">
          Read More
        </button>
    </a>
    {% endif %}

    </div>
</div>

web/templates/projects/detail.html
{% extends "base.html" %}

{% block page_content %}
<div class="col-lg-8 col-md-10 mx-auto">
  <h1>{{project.title}}</h1>
    <small>{{project.description}}</small>
    <hr>
    <br>
    <div class="card-deck">
        {% for component in project.component_set.all %}
        {% include "projects/component.html" %}
        {% if forloop.counter|divisibleby:"2"  %}
    </div>
    <div class="card-deck">
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

web/templates/projects/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="col-md-8 offset-md-2">
    <div class="card-deck">
        {% for project in object_list.all %}
        {% include "projects/card.html" %}
        {% if forloop.counter|divisibleby:"2"  %}
    </div>
    <div class="card-deck">
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}